Losses:
      L1Loss: 
            weight: 1.0
      StyleGanLoss:
            weight: 0.1
            coef:
                feature_weight: 0.1

Optimizer:
        type: Adam
        beta1: 0.0

# convert net from "(noise -> conv) to (like style-gan mapping(noise)x18 -> lantent -> Encoder + Decoder.)"
Gen:
        lr_mul: 1

# fix bug in symmetricSplatting.
